Support collection grouping
NotionX/react-notion-x pull request #182
Opened 2021-12-12 15:32 UTC by hcorta

PR for collections-grouping support 🙂
I'd willing to hear suggestions on code style or similar.

2021-12-13 21:16 UTC, normdoow commented
Thanks @hcorta will be looking at this over the next couple of days.

2021-12-15 23:36 UTC, normdoow commented on example/next.config.js
> -        destination: '/067dd719a912471ea9a3ac10710e7fdf',
Can we reset this back to what it was?

2021-12-15 23:36 UTC, normdoow commented on example/pages/[pageId].tsx
> +  const rootNotionPageId = '6fa923939ba54d7583612a68a6467e34'
can we reset this back as well?

2021-12-16 00:59 UTC, normdoow commented
Could you make your notion page at `6fa923939ba54d7583612a68a6467e34` able to be duplicated so I can add it to our Notion test suite at https://travis-fischer.notion.site/Notion-Kit-Test-Suite-067dd719a912471ea9a3ac10710e7fdf? Thanks!

2021-12-16 01:11 UTC, normdoow commented
Doing some testing. I'm not seeing my two rows in group 1 and group 2.
![image](https://user-images.githubusercontent.com/21371266/146289502-0380b9c6-831e-4598-8406-ffc3a2410256.png)
Testing this page: https://travis-fischer.notion.site/dd5d904fb13d402cbba6d6bdfecfa181?v=83a14203fe024932b711767c22819b39
Trying to figure out why.

2021-12-16 01:12 UTC, normdoow requested changes
Just a couple of things. Code looks good! Just need to make sure its working on the case I found. Thanks!

2021-12-16 10:47 UTC, hcorta commented
@normdoow sure, let me review those things. I noticed as well that when selecting the "Hide empty groups" option, the hidden property is not explicitly received. I'll check on that.

2021-12-17 21:16 UTC, hcorta commented
@normdoow a few things:
* I restored default values as required.
* I created this template, hope that helps: https://hcorta.notion.site/Collection-Grouping-671539f6022c4327a1f6de8069db3abe
* I could not solve the "Hide empty groups" issue. I could not find anywhere (collectionData, collectionView, etc) the info from where I could filter those groups.
* I could not replicate your case, may you give me more info? 
* The board collections needs to be reviewed when a second groupBy is applied, but that could be motive for another PR?

2021-12-17 22:37 UTC, normdoow commented
> @normdoow a few things:
> 
> * I restored default values as required.
> * I created this template, hope that helps: https://hcorta.notion.site/Collection-Grouping-671539f6022c4327a1f6de8069db3abe
> * I could not solve the "Hide empty groups" issue. I could not find anywhere (collectionData, collectionView, etc) the info from where I could filter those groups.
> * I could not replicate your case, may you give me more info?
> * The board collections needs to be reviewed when a second groupBy is applied, but that could be motive for another PR?

All good. I think we will be ready to merge this in once we make sure the issue I was seeing where the rows aren't showing isn't an issue. We can wait for another PR for the board collections.

So testing on your notion template, I get the no description list rows but not the rows for the other groups.
![image](https://user-images.githubusercontent.com/21371266/146615361-ec70caef-bf37-4fd9-a33b-65bbecc9ed62.png)
Looking into the returned data. For some reason that data isn't coming back from the notion-client query endpoint.
![image](https://user-images.githubusercontent.com/21371266/146615457-9069444f-643f-4aec-a068-196d874d2876.png)
The `blockIds` is an empty array.
Pretty sure I have your fork pulled correctly to test from it. Trying to think what else this difference could be from.

2021-12-18 12:25 UTC, hcorta commented
@normdoow I see. It seems like I missed something for multi-select groupings.... I'll check on that. Thanks for investigating a little further the problem 🙂

2021-12-18 14:32 UTC, hcorta commented
@normdoow I thought about adding a prop to the **NotionRenderer**, _**hideEmptyGroups**_ for filtering groups with no children. Would it make sense?

2021-12-20 22:37 UTC, normdoow commented
> @normdoow I thought about adding a prop to the **NotionRenderer**, _**hideEmptyGroups**_ for filtering groups with no children. Would it make sense?

Hmm not sure if we need that. Notion allows that as an option correct, but by default it shows empty groups. So I'd say lets just let it be the default for now.

2021-12-21 16:44 UTC, hcorta commented
@normdoow I solved the issue with the multi_select grouping. It should be all ok now.

2021-12-28 19:14 UTC, normdoow commented
Hey @hcorta, I haven't been able to complete reviewing this. Been off on vacation. I'll be able to get to it hopefully in a couple of days.

2022-01-04 15:29 UTC, normdoow commented
@hcorta, everything is looking good. The only thing that I am seeing is that not all the data for boards view is showing up.
I'm fine with not having board views work with multiple groupBys for this PR. But we should be able to get it to work with one as it was perviously.
This is the page id I was seeing the issue on: ba528cc0a8dd41bcb74c7e9f80a4785d
On Notion: 
![image](https://user-images.githubusercontent.com/21371266/148082402-8c7f1184-d9d1-4695-9394-24174656c235.png)
On react-notion-x:
![image](https://user-images.githubusercontent.com/21371266/148082446-691accf7-621d-4bc3-8d7f-b251b59c2c50.png)

2022-01-04 15:35 UTC, normdoow commented
@hcorta looks like we are getting the correct data for the board. Just not showing it correctly. I'm looking into it right now to see if I can fix it.

2022-01-04 16:02 UTC, normdoow commented
I figured out the issue.
![image](https://user-images.githubusercontent.com/21371266/148087382-9ff414c7-ca2e-4e4b-856b-a797ee0e3a23.png)
In collection-view-board.tsx

2022-01-04 16:13 UTC, normdoow approved these changes
Great job on this @hcorta. Thanks for the help. I'll that fix after merge.

2022-01-04 16:14 UTC, merged

2022-01-04 16:25 UTC, normdoow commented
Live on v4.13.0 💪

2022-01-04 16:44 UTC, hcorta commented
Thanks @normdoow! Glad to help 😊

2022-02-04 14:01 UTC, adlpz commented
Hi! I haven't looked to much into it but I've found the Gallery view fails in 4.14.2 with `TypeError: Cannot read property 'blockIds' of undefined`. The stack trace refers to `node_modules/react-notion-x/build/cjs/components/collection-view-gallery.js:31:166` and I have feeling it's related to this change.

Reverting to 4.11 fixed the issue.

I'm writing just to give the heads up in case it's something trivial that was missed. Otherwise, if I have some time, I'll look into it.

2022-02-04 14:33 UTC, hcorta commented
Hi @adlpz, could you share the Notion page you're trying to render?

2022-02-07 11:19 UTC, adlpz commented
@hcorta Hey, it was a simple page with an inline Gallery database, just for testing. Here's the public link: https://prealfa.notion.site/Blog-d99da35d2fbd42f189a9ad74c158aee7