fix github links, refactor dates, tweak styles
NotionX/react-notion-x pull request #285
Opened 2022-05-04 22:13 UTC by Commandtechno

# Description

Now handles inline external object instances separately
Fixes #283 

<details>
<summary>Refactored dates</summary>
<br>
Also noticed that dates were handled a bit weird, so I added getNotionDateTime which returns a Date, and simplifies a lot of operations
</details>

<details>
<summary>Added dark mode support for the GitHub logo</summary>
<br>
This applies to many more icons, but that is for another time

![image](https://user-images.githubusercontent.com/68407783/166833840-2c6df285-8a53-4a08-9c0e-2a9629c69090.png)
</details>

<details>
<summary>Made the GitHub icon fit the text</summary>
<br>
Before: 

![image](https://user-images.githubusercontent.com/68407783/166832975-18059ed5-68dd-49fc-87fd-ccba7efd5537.png)

After:

![image](https://user-images.githubusercontent.com/68407783/166833042-470d996f-9c52-4ea5-a37d-8a33767c02d8.png)
</details>

<details>
<summary>Removed random empty ruleset</summary>
VSCode picked it up so why not
</details>

# Notion Test Page ID

https://react-notion-x-demo.transitivebullsh.it/e648a7762fee458bb3b50ae946cb3c86
https://react-notion-x-demo.transitivebullsh.it/767f227505f548a28efefbc5da8831ff

*this took me way longer than I would like to admit*

2022-05-04 22:59 UTC, Commandtechno commented
Oops, meant to make another pull request... Not sure how to revert it, so 2 in 1.

Fixes width and scaling issues with the Spotify and Figma embeds at https://react-notion-x-demo.transitivebullsh.it/5d4e290ca4604d8fb809af806a6c1749, removing the need for the `notion-asset-wrapper-full` class.

Also removes a weird white background on iframes visible in dark mode.

2022-05-10 22:52 UTC, transitive-bullshit requested changes
Thanks for the PR 💯 

Unfortunately, PRs with multiple unrelated changes make it really, really hard for me to quickly reason about whether or not there could be unintended consequences.

In the future, if you want your PRs to be merged, try to keep them as focused on doing one thing as possible, especially if it's your first PR to a project.

I think there are definitely good changes in here that I'd love to merge, but I don't have the time to reason through everything or pick and choose what to merge and what to ignore.

Hope that makes sense && thanks again.

2022-05-10 22:52 UTC, transitive-bullshit commented on packages/react-notion-x/src/components/eoi.tsx
> +import { formatDistanceToNowStrict } from 'date-fns'
I'm trying to avoid importing from `date-fns` in the main bundle because it adds quite a bit to the bundle size.

2022-05-10 22:52 UTC, transitive-bullshit commented on packages/notion-utils/src/get-page-property.ts
> +              return getNotionDateTime(
this use to return an integer (`getTime()`), but now these code paths are returning dates, which makes it hard to reason about the change in isolation

2022-05-10 22:52 UTC, transitive-bullshit commented on packages/react-notion-x/src/components/eoi.tsx
> +  if (!original_url) {
i really like the removal of our reliance on attributes

2022-05-10 22:52 UTC, transitive-bullshit commented on packages/react-notion-x/src/components/eoi.tsx
> +      externalImage = <SvgTypeGitHub fill={darkMode ? '#fff' : '#161614'} />
this fill doesn't have to rely on `darkMode`. I'd rather have it use the currentColor and have this logic be handled strictly in CSS

2022-05-10 22:52 UTC, transitive-bullshit commented on packages/react-notion-x/src/icons/type-github.tsx
> +        <path d='M128.00106,0 C57.3172926,0 0,57.3066942 0,128.00106 C0,184.555281 36.6761997,232.535542 87.534937,249.460899 C93.9320223,250.645779 96.280588,246.684165 96.280588,243.303333 C96.2805
removing the hard-coded fill is a good call, but i'd rather use fill=`currentColor` and have the fill come from css

2022-05-10 22:52 UTC, transitive-bullshit commented on packages/react-notion-x/src/components/asset-wrapper.tsx
> -        value.format?.block_full_width && 'notion-asset-wrapper-full',
i'm pretty sure this is used for certain full width blocks and won't render faithfully without this

2022-05-11 20:37 UTC, Commandtechno commented
Sorry about that, still figuring out git... for simplicity, I'll be closing this pull request and opening separate ones. Thanks for the feedback!

2022-05-11 20:37 UTC, closed without merging

2022-05-11 20:51 UTC, transitive-bullshit commented
@Commandtechno it's no worries 😄 Your work is definitely very welcome — it just helps OSS maintainers like myself a lot to have things be more focused.

Thanks again 🙏