fix: numbered_list number
NotionX/react-notion-x pull request #437
Opened 2023-02-17 13:43 UTC by zhiwen95

#### Description

fix numbered_list number priority use notion value(list_start_index) 

- notion view
<img width="779" alt="image" src="https://user-images.githubusercontent.com/14962143/219668499-f9bb5daf-b15b-4a08-a0bb-1af17805bb37.png">

- actual view
<img width="789" alt="image" src="https://user-images.githubusercontent.com/14962143/219668031-1e9e3798-5f88-4fe0-b85e-39503a2650d5.png">

- expect
<img width="748" alt="image" src="https://user-images.githubusercontent.com/14962143/219667757-02c7086c-22b7-4a18-974a-3027bcb3d0c7.png">

#### Notion Test Page ID

237e024b82a044b090f53de9f05f1469

2023-03-02 14:39 UTC, transitive-bullshit requested changes
This change looks great @zhiwen95 🙏 

Just remove the console.log

2023-03-02 14:39 UTC, transitive-bullshit commented on packages/react-notion-x/src/utils.ts
> +  console.log(blockMap[blockId].value)
make sure you remove the log before I can merge

2023-03-13 02:27 UTC, closed without merging

2023-06-29 14:02 UTC, xll-dev commented
why closed? it's clearly a react-notion-x bug and need be fixed, and here the PR is! @transitive-bullshit @zhiwen95

2024-04-13 14:57 UTC, PascalPixel commented
Bumped into this issue today, to match Notion, we should use `list_start_index` for `<ol start={*here*}>` @transitive-bullshit 

```json
"c392ce6b-7a14-4f85-a174-a353c86fa8e2": {
      "value": {
        "id": "c392ce6b-7a14-4f85-a174-a353c86fa8e2",
        "version": 1,
        "type": "numbered_list",
        "properties": {
          "title": [
            [
              "Enable Your Extension",
              [
                [
                  "b"
                ]
              ]
            ]
          ]
        },
        "format": {
          "list_start_index": 3,
          "copied_from_pointer": {
            "id": "c285e614-f061-40bf-95f1-e3304d01f60a",
            "table": "block",
            "spaceId": "e0ec446f-35df-4eab-a245-54d33ff60649"
          }
        },
        "created_time": 1712772102685,
        "last_edited_time": 1712772102685,
        "parent_id": "79ff28e4-b9cc-45b7-ab2a-f19970879a71",
        "parent_table": "block",
        "alive": true,
        "copied_from": "c285e614-f061-40bf-95f1-e3304d01f60a",
        "created_by_table": "notion_user",
        "created_by_id": "c5d99c6c-da3b-487f-82a7-b11cd5db3add",
        "last_edited_by_table": "notion_user",
        "last_edited_by_id": "c5d99c6c-da3b-487f-82a7-b11cd5db3add",
        "space_id": "e0ec446f-35df-4eab-a245-54d33ff60649"
      },
      "role": "reader"
    },
```